ansible_become_pass: ENC[AES256_GCM,data:hcQwk9za+I8VQlA=,iv:TegWQIs7QvpJtxJ64CEEpJplCSiBvoMH17zbFtOQJ68=,tag:oLWGFKRuVDvQLNP1l83wjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h8wrq59wx0653vfnmd627nr96k97kss7xem9tqurhcgygzhcx4cs8vqdl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzT2dFT2NFWXFNOTZVYk5m
            Z2xQL3VCWnYzdGoxRVZ1MkFpOVFDZVhYZWdrCkFKak5UVnRacjE4RDlDbWE4Rmgv
            dGtsMWpPZ1d1K1Z2VTBxQm1oSFp3MUUKLS0tIHZVMitMdnl4Y0lGYXVaK0M3cHFH
            RFh5elBkaW1rZ0RqQVZXL2UwVG5aWnMKRTwq8iKD5ZyIf5r9KPGtBJRSBBu4sg5C
            i3UgpieIC+fP4jxB7MsE+HANOcFViNFROHBV3Qd+x+PBDqIohTfpqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-26T03:33:46Z"
    mac: ENC[AES256_GCM,data:mXC/2qWv7xHIj0wfLctpUy+oFUeDSp4orUwuRYBPnABzouajkTVQRaFrI1lawIajos63vo4ay8bzTYLvFNtohn6go2QLguRertcf6/6XH39mbhjbolLvc66p4WPrf35vGlihAvT29ypKO5KDtlDtwk1Hk2+VVY3eVkd6xsXk1V4=,iv:PjzKRHssEF8SG5rodnv76AFEQd8456duT+X2tk267NQ=,tag:3KX0KGtjd1vInONmForX3w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
