apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:rgZMO7Lnm/VVr5XoPkaTRxkIeMMhEhbp,iv:l+El1Hjo5ZnOM/ffk4+HwL72YWxOiSoHXq7U87+BfoI=,tag:+J8f8gUymwnWAKPudWKbWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h8wrq59wx0653vfnmd627nr96k97kss7xem9tqurhcgygzhcx4cs8vqdl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQmtjaXR5aWJNbDkrYVVn
            QnRwWitwMDBvbmJXNTIyZE56MlpxQU1zTDNFCnNtMUNKQWtNWmE2bFhvS3JHV0hy
            UGN5V1pMU1lJL3RpZ0tFbVVPU2tkZEUKLS0tIDgyaUxGUHlVOThrYVovazcwZS94
            a0RacG54N1Frdm5vR1Bla2dGbW9idTgKNmKCEgYa6p2BG8tbfsM13fFBY4O+x/+T
            Sm5UPqcdHrT7eDvUGFU7bBw1Ba5oygL+mhS/iUS8etwy0w5rrnZdXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-13T18:33:53Z"
    mac: ENC[AES256_GCM,data:FcML3pcY0IdUQYgq6ar0mYTjCuR1TiNvEQXFS19u3m2CNv8uRFILjlAD8k9khhOznLxFw70OUYHshc+PY+4+5g+XkMfpdn3LM7otG/uN55KGmijTu+/rdv+unsPS9zDRjrqEqBYcRBlGsjDr3mZhq3bi3Nd+c+WlSsRt+rsD6/U=,iv:xOxm3jNEfwMDUlkfX9tJtgMkk70jlBP6UGNAozfWxL8=,tag:Aj5QP/3rdTNWxuADfWmcfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
