apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:aic11TVKMpswYLXsVTnVVl5VQMfvkvjq,iv:fkSEHVWuNT1hdWEiNIt5BAGY0/eJvpu2zpBJMnyNVxY=,tag:pMqvm6+UVmdQujG0vsgvog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h8wrq59wx0653vfnmd627nr96k97kss7xem9tqurhcgygzhcx4cs8vqdl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRGhPYVZERURuU2V6S0hi
            RStZakFFOVNveVMxVk9rMVdIUU5jRzB5UEhNCjN3bCs2QVlOZXpVa0NEWUREaFpD
            ekhTRklrY094dDBhLzJhbWkyMVZsUFEKLS0tIDc0c2Q3VU9zdmVvaUErd2J3NFRi
            ZXZkbkVrRWtzeWlvYjZqdjNTMFBqU00KXcCdcVLOH4liCuTDgQxUj7aIk6Q5sHuM
            wbA/8sH0PStCUKOa/maDVhjdlPGqQsrWANCPpy/Jk0R2zVd9Juin7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-26T03:34:16Z"
    mac: ENC[AES256_GCM,data:hq4L0b34kw1mKsaxrydlJnGR2NdDPqXId80OiLiry4DcfnuWeNJnQ7ql1L2BC/eE1+lN/4zQQlQ36Is3oAAZlZjQ4q3YifjcWhe0f9NN6boNkm6A+2Q2SHafF4AKISv7+w3Xx8tSWODNn9Qfv/zEBTDzkMIDP2sPKjcjZIcyHtQ=,iv:9pDxvp5CvwPmlUxvhrdMZ5/dZtErqeg3WaD6vWHm2co=,tag:6fc0EpLR5WZ02VjBV2jdRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
