apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:6PaPsX0jomNxpm4kdg1XFMwjHyJ/OZjTuPFkA20idXRDhsZRkYh5ZQ==,iv:8gcLMl0fn8Qfu7xIjmt6s4vm6MmFIO9euQfM4DHg7Os=,tag:0uOvXp1FPQ+ducLyQxHI4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h8wrq59wx0653vfnmd627nr96k97kss7xem9tqurhcgygzhcx4cs8vqdl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NldaeE9qUFAxYTc4T2ky
            bVNpb3owck0yaXpRNUlZeGJ1UlhBZDNZSWhnCm44a2R3VUQ4M29UMlBoOSt1dnhu
            RjM0YWJQVkJjZXROVkZSU1g0YXVqM0EKLS0tIGNNTTVFbFdxNzVBZG0zQ3MrTEky
            eWVJZ3RQNmtxZzd4OHdFT3BHNTFmOEEKwPJg0n49J4+5OZ2hgUt9B/+Q8Dr+zrWU
            K6es2Wsv01egkdtiQf9zF1pfdJp3QorEaY5qCEmtvKIQUZs/AGDkcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-26T03:34:16Z"
    mac: ENC[AES256_GCM,data:+2mydOpQZSttU2N+775gws/Ae9hMKm56KkeO/hLfLSgm+Un+9OfoOTIgI+V2TIKCJJm/a9yi6YlBt68WjVV1VIumlnTMWsjBHMw/VMaMFFgZ/qCokhWI/XvZyShAHu6SfagwwCufa+40GuLyFlpl59KIUoljqe7n5sebPWjUxDM=,iv:i8tAQNBYGCFg+lw2LNDlWXthVWcdVmMYEeGb8nM4vQo=,tag:Ra3cQdepz6U4ihAyEYEsdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
