apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:RReh+HFrAhUySnX5KTwTUUAUnlfe38bD68N8w7Se96F/UrKaqPRu2g==,iv:hQzlDWnwQTsyRBbouGdeq4JV5wazinM4A/mGEaYSGwk=,tag:w1wO072DoQF90nCZvJRvbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h8wrq59wx0653vfnmd627nr96k97kss7xem9tqurhcgygzhcx4cs8vqdl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTnd0dTlNVDB2S2xjRkNC
            WXZkQndvNTF0ZDBrQ2haanV1TXptZk8zQ1Z3CnBzcmlncldPMXh3T3NVSDdLUHg0
            ckQ5a1ZYNDFyeXlhNy9wUEhzRitRTjAKLS0tIG9kMXFadkZoMitjSmRTR2tiNm96
            T1dxb09XRHVtUEdWT3gxeElxQTJQcU0KELaExnGdIwzjhD5fw+dpjqGnqLFzBdns
            OwibB3i3ETxiZN7KlLqRRAeqdnOK23hyeAjl8ubaEcquxUBWnise5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-13T18:33:53Z"
    mac: ENC[AES256_GCM,data:LHRrQsEwmaJ7wfClVzEyOd5vnrD0enqSO7ZpxGbTbYsvHXqcRexRtFGrfDpbyyMY2818glxyRnaSktDETSDoC4icvW1McuPyENLf1XwH8GkVTNQ5+AfsAQ6twlvhtzmMnnkTd/xaG8kbKX2bH4otEP9cLD85r8C3+g5PDQPzJYM=,iv:gX5xtO5T0vKg106VPMQ1WemV3++xusDkRD1fR5Ykg+o=,tag:2DL+zC/WzWJsEuPsrQVxcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
