apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:mkSsFlrsymjAe5wb,iv:aMyHsFUOzig5+B4KzMzN+iNP0+fsouK8RdYL0PZ4Nbk=,tag:mkQASQzc9Yqy0da9ZoEBew==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:B22pzZ7Y/QMri+eYBaVUuqtsWMNVwxhTlZH/8HhY5Abw/+GK,iv:Y7iTBOzsnzB828gRcf5h0sp1Smtja7ZEHOPsUs1Jq1I=,tag:tyFvMU30nCIg9EZP4cwZGQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:4f1xTosCWi3YVsnecuuU,iv:wN2IGtVvNFhA3Qi3mwlRKwfbGJHpnysAAsllU5dZdP8=,tag:JKLYGgKSNhoy3hL9xAJ9Yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h8wrq59wx0653vfnmd627nr96k97kss7xem9tqurhcgygzhcx4cs8vqdl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQUZHREdWOVRLUG9jTlBa
            RjNGNStVUXdDRXJnWHF6ditJQUR6MXFWVURNCm14Wjl4ZVpETG1qa1RsSXI4OWpM
            bDBsaUhrREkzclNFZWQ2UWxOVS9pcWMKLS0tIEx3M096YlBVbWt4dDNsMnF4T3N5
            c3doN2dLYVVHMFRsUUsveWtVelFMTW8KZ5G5MuQZNGzrtV/T6Ej8WWCYfRof68L1
            XbXFjuZTPlmaivfmLWE2WQWrZFvc4ic4kTeFYiov+79qxmeJDV3aUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-26T03:34:17Z"
    mac: ENC[AES256_GCM,data:3MaE28vrjW6DDJLWzkcaINZ59z0bL1ZwT5ilEdvp6oLG442EoVHv43Nn2FTGlesV2frq05bnvqhtAqQjnnxJu80f18p59FvnLsVZr+98tAhyFrGAJbs04CnpjIuII8NBFLx+hMKHq85fsKyfAYI77lRetnqFOf+cESjgNjGhKi8=,iv:8J7oNygVD3XKQiH69hKGCLhaVPYHzxJCX6UHqSODqCE=,tag:wq99p97D/8XdQJ4OiGg/zQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
