apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:/w6p8aoDR2nKajs4,iv:cUt1OhV+3d4DBVyN7RMSrvZwsINuEWkg3SaIRZlt/x4=,tag:aRuc/YxYcv6y3N1unyfYwA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:cI+ffEbUQgwvXNH7D3yDGIObmG1QIb3k/fcF3Pnt29qKVXKL,iv:brckdtIaZbQbnukGaiWd93gqa9riAWcZdHiFKF0DEtw=,tag:64jaj7MVvrh9ZXNPrWbWrA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:046625/nJL8//i8YZzBs,iv:sqA2Escgkt1/KNVHUNMZLmNhybc+rlbtihJY0wbAyvY=,tag:OQiOFiNSK/eG8UD99D4qOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h8wrq59wx0653vfnmd627nr96k97kss7xem9tqurhcgygzhcx4cs8vqdl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTVBmNTJlR3g0UWEwSHhl
            MWFJbFUwTm1DR01HUlZEd1JzUXdEQUJtN1U4Clg2NlJZVXFXWENSUXhUWm96NkFv
            Vy9rZ2ZteVhnZFpEL2MyWVVDMzZTUk0KLS0tIEhMUHZEcEJodE9OTmVSalFzMVpo
            M2FPVkdRZjlTRUNmdGlPSFJRd2p2WVkKsfUokIufl1kAw6H185PONYSF5eqztJIw
            gIdyStPJOi7ICSM7wbECDaOmc/pOfu5RdxbkZR4PkaITLJjvf7cxRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-13T18:33:53Z"
    mac: ENC[AES256_GCM,data:mMMP0JMOtsnRbzUqghqqxaTv733S3mlh0KN+QoWb4RW4BkiNrMr2XBdjsUQquH+2QxNZyLVHe1a1LW4dp+6GgkOIKXtDNh3OwhHjHbC9oyBCoUEuUUTGz6s64py7qwKhzR4O5JOwS3jw3rKG1HRN6Lilwi0RWFN4h9pQsb2YVIE=,iv:I/2prjmnaEJAN8p+jvPJw/ktr6iByeeWyuytM4kFKMQ=,tag:9mQ6NkkWR0yvMe/T+6T57g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
