apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:S7C12HXrBpi0gii62MmCo1kZvPyCmeavZNqeWWZSYag8ipI+,iv:GD3HzzVFijUZLdQ6coLK1l5B3YcJ77PEOAREMvA6a/U=,tag:u4/epeeG4dPrGj+DWFgbNg==,type:str]
    credentials.json: ENC[AES256_GCM,data:pDeNExO/T5Bi8oH23IsVJeKVsr0HHSH/U55YAJoahSoMol6M32srjOjsNTE35EBOujFczCv/JWyl8PDotfHkjap53qJU7TgOB8ITI9/tlEIsHnbyj+6ygl1D6rK5kvXe7+Vo9uN7kjQ2vDVZFSN58ChUsU/fJ65ZF1/jSq8it0NhSUNnmp2Z4yRqHtX/Ds/TamAoiynwQi/lNHhkVKBP4xTMv4CDQQ3vwPl2+EicvQ==,iv:0AVvDcmiEGYLw4jXk+T1VIgQ/Dd0VjfzT1FJBEsHMms=,tag:8/dyq5Sh/N+hzDL7AKfZDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h8wrq59wx0653vfnmd627nr96k97kss7xem9tqurhcgygzhcx4cs8vqdl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Ky9qbm9Ob0tLS2NITU9h
            WDJoOWdhTXpCd0xpM3ZEMW40MWJERVNTaGhzCjlwN0dQSGE1RkVFNVlFY1VQekxk
            THZrYVFMODZLekxjRlpPTldhM0FrUm8KLS0tIHBIT1hXSllrc2JxVzRKNVFBYjVQ
            ZTVKQnROcEd6VFNTR0tMSXB5cVIwSDgKi7z8NHAVjlWqoZbc/7NuZucY0QmvkEuv
            9OhzqklKkGMSbT/dNRzqVogA4MEedj/7vrjdwmbR1ENvNv/VPKFs4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-13T18:33:53Z"
    mac: ENC[AES256_GCM,data:COTEmRb3dlxGFYOTiDSvOfHIjITtCbFL5FJ5Khi+aawsjHZBEXAMg7NbgqA17iyKjkFfOoMeAfxbK9JZG06IklpGVKtH22PSAr/W2FTh/v9i5r4vVzV2XT7FPaQMf+1xlu/760apm6HDMDIh2gyqlIYvwAoBD6p4A9M1lEpEndg=,iv:ZEhEi7AFjz0K3N+ByzYq3LfOGwvrb8TBlCN5xPTseJ8=,tag:ZZRhdodZA622ByQTUX3yhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
